# Site settings
title: Ramon Viñas
description: I am passionate about machine learning. Concretely, I am interested in the theoretical foundations of deep learning as well as its applications in science and medicine. My long-term goal is to use machine learning to enhance high-impact scientific and healthcare advances.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ramon Viñas
user_description: I am studying the MSc Degree in Machine Learning at University College London. I am interested in the theoretical foundations of deep learning as well as its applications in science and medicine. My long-term goal is to use machine learning to enhance high-impact scientific and healthcare advances.
user_title: Machine Learning Engineer
email: ramon.torne.17@ucl.ac.uk
# twitter_username: lorem_ipsum
github_username:  rvinas
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
